Repository SEOULMILK-1/SEOULMILK1_BE, pull requests merged in 2025-03, with the labels that each got.

#19 [FEATURE] 본사 관련 기능 구현
  .gitignore
  build.gradle
  src/main/java/SeoulMilk1_BE/auth/controller/AuthController.java
  src/main/java/SeoulMilk1_BE/auth/dto/request/SignUpRequest.java
  src/main/java/SeoulMilk1_BE/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/SeoulMilk1_BE/global/config/QueryDslConfig.java
  src/main/java/SeoulMilk1_BE/global/config/SecurityConfig.java
  src/main/java/SeoulMilk1_BE/nts_tax/domain/NtsTax.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/HqTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/HqTaxResponseList.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/post/repository/init/CommentInitializer.java
  src/main/java/SeoulMilk1_BE/post/repository/init/PostInitializer.java
  src/main/java/SeoulMilk1_BE/user/controller/AdminController.java
  src/main/java/SeoulMilk1_BE/user/controller/HqController.java
  src/main/java/SeoulMilk1_BE/user/controller/UserController.java
  src/main/java/SeoulMilk1_BE/user/domain/Team.java
  src/main/java/SeoulMilk1_BE/user/domain/User.java
  src/main/java/SeoulMilk1_BE/user/domain/type/Role.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqSearchCsNameResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqSearchCsNameResponseList.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqSearchCsResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqSearchCsResponseList.java
  src/main/java/SeoulMilk1_BE/user/dto/response/PendingUserResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/UserResponse.java
  src/main/java/SeoulMilk1_BE/user/exception/TeamNotFoundException.java
  src/main/java/SeoulMilk1_BE/user/repository/TeamRepository.java
  src/main/java/SeoulMilk1_BE/user/repository/init/TeamInitializer.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
  src/main/java/SeoulMilk1_BE/user/service/AdminService.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
  src/main/java/SeoulMilk1_BE/user/service/UserService.java
Labels: 📬 API, ✨ Feature

#32 [HOTFIX] 회원가입 관련 수정
  src/main/java/SeoulMilk1_BE/auth/controller/AuthController.java
  src/main/java/SeoulMilk1_BE/auth/dto/request/LoginRequest.java
  src/main/java/SeoulMilk1_BE/auth/dto/request/SignUpCSRequest.java
  src/main/java/SeoulMilk1_BE/auth/dto/request/SignUpHQRequest.java
  src/main/java/SeoulMilk1_BE/auth/service/AuthService.java
  src/main/java/SeoulMilk1_BE/user/controller/AdminController.java
  src/main/java/SeoulMilk1_BE/user/domain/User.java
  src/main/java/SeoulMilk1_BE/user/dto/request/UpdateUserRequest.java
  src/main/java/SeoulMilk1_BE/user/dto/response/PendingUserResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/UserDetailResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/UserManageResponse.java
  src/main/java/SeoulMilk1_BE/user/repository/UserRepository.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
Labels: 🐞 BugFix, 🔨 Refactor

#29 [FEATURE] 게시글 목록 조회 기능 구현 및 조회 관련 응답 값 수정
  src/main/java/SeoulMilk1_BE/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/SeoulMilk1_BE/global/service/S3Service.java
  src/main/java/SeoulMilk1_BE/post/controller/PostController.java
  src/main/java/SeoulMilk1_BE/post/domain/Post.java
  src/main/java/SeoulMilk1_BE/post/domain/type/Type.java
  src/main/java/SeoulMilk1_BE/post/dto/request/post/PostCreateRequest.java
  src/main/java/SeoulMilk1_BE/post/dto/response/post/PostDetailResponse.java
  src/main/java/SeoulMilk1_BE/post/dto/response/post/PostListResponse.java
  src/main/java/SeoulMilk1_BE/post/repository/PostRepository.java
  src/main/java/SeoulMilk1_BE/post/repository/init/PostInitializer.java
  src/main/java/SeoulMilk1_BE/post/service/PostService.java
  src/main/java/SeoulMilk1_BE/post/util/PostConstants.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#33 [FEATURE] 게시글 고정 API 하나로 통합
  src/main/java/SeoulMilk1_BE/post/controller/PostController.java
  src/main/java/SeoulMilk1_BE/post/domain/Post.java
  src/main/java/SeoulMilk1_BE/post/dto/response/post/PostDetailResponse.java
  src/main/java/SeoulMilk1_BE/post/dto/response/post/PostListResponse.java
  src/main/java/SeoulMilk1_BE/post/service/PostService.java
Labels: 📬 API, ✨ Feature

#35 [REFACTOR] 유저 정보 조회에 이메일 추가
  src/main/java/SeoulMilk1_BE/user/dto/response/UserManageResponse.java
Labels: 🔨 Refactor

#37 [REFACTOR] 회원 삭제 관련 기능
  src/main/java/SeoulMilk1_BE/auth/controller/AuthController.java
  src/main/java/SeoulMilk1_BE/user/controller/HqController.java
  src/main/java/SeoulMilk1_BE/user/domain/User.java
  src/main/java/SeoulMilk1_BE/user/repository/UserRepository.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
  src/main/java/SeoulMilk1_BE/user/service/AdminService.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
Labels: 🔨 Refactor

#40 [REFACTOR] 세금계산서 관련 수정
  src/main/java/SeoulMilk1_BE/nts_tax/domain/NtsTax.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/CustomOcrResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/HqTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/OcrService.java
  src/main/java/SeoulMilk1_BE/nts_tax/util/TaxConstants.java
  src/main/java/SeoulMilk1_BE/user/controller/HqController.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
Labels: 🔨 Refactor

#39 [FEATURE] 지급결의서 PDF 파일 생성 및 다운로드 API 구현
  build.gradle
  src/main/java/SeoulMilk1_BE/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/SeoulMilk1_BE/payment_resolution/controller/PaymentResolutionController.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/request/PaymentResolutionRequest.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionReadResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
  src/main/resources/templates/NanumBarunGothic.ttf
  src/main/resources/templates/payment_resolution.html
Labels: 📬 API, ✨ Feature

#43 [FEATURE] 대리점 홈 관련 기능
  src/main/java/SeoulMilk1_BE/global/service/S3Service.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/CsApprovedTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/CsApprovedTaxResponseList.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/CsRefusedTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/CsRefusedTaxResponseList.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/NtsTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/user/controller/CsController.java
  src/main/java/SeoulMilk1_BE/user/service/CsService.java
Labels: 🔨 Refactor

#44 [HOTFIX] 지급결의서 관련 수정사항 반영
  src/main/java/SeoulMilk1_BE/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/NtsTaxService.java
  src/main/java/SeoulMilk1_BE/payment_resolution/controller/PaymentResolutionController.java
  src/main/java/SeoulMilk1_BE/payment_resolution/domain/PaymentDetails.java
  src/main/java/SeoulMilk1_BE/payment_resolution/domain/PaymentResolution.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/request/PaymentResolutionRequest.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/request/PaymentResolutionUpdateAccountRequest.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
  src/main/java/SeoulMilk1_BE/payment_resolution/utils/PaymentResolutionConstants.java
  src/main/java/SeoulMilk1_BE/user/controller/HqController.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqWaitingNtsTax.java
  src/main/java/SeoulMilk1_BE/user/repository/init/TeamInitializer.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
Labels: 🐞 BugFix, 🔨 Refactor

#47 [Hotfix] 지급결의서 관련 수정사항 반영
  src/main/java/SeoulMilk1_BE/payment_resolution/controller/PaymentResolutionController.java
  src/main/java/SeoulMilk1_BE/payment_resolution/domain/PaymentResolution.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/request/PaymentResolutionRequest.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionListResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionReadResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepository.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
Labels: 🐞 BugFix, 🔨 Refactor

#46 [FEAT] 본사 담당 대리점 관련 기능
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/HqTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/user/controller/HqController.java
  src/main/java/SeoulMilk1_BE/user/domain/User.java
  src/main/java/SeoulMilk1_BE/user/dto/request/HqAddManageCsRequest.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqManageCsResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqManageCsResponseList.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqWaitingNtsTax.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
  src/main/java/SeoulMilk1_BE/user/util/UserConstants.java
Labels: ✨ Feature, 🔨 Refactor

#49 [HOTFIX] 지급결의서 목록 조회 시 전체 개수 포함하도록 변경
  src/main/java/SeoulMilk1_BE/payment_resolution/controller/PaymentResolutionController.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionFindListByOptionsResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionListDetailsResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/response/PaymentResolutionListResponse.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepository.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
Labels: 📬 API, 🔨 Refactor

#51 [REFACTOR] 대리점 관련 수정 사항
  src/main/java/SeoulMilk1_BE/user/dto/request/HqAddManageCsRequest.java
  src/main/java/SeoulMilk1_BE/user/repository/TeamRepository.java
  src/main/java/SeoulMilk1_BE/user/service/HqService.java
  src/main/java/SeoulMilk1_BE/user/service/TeamService.java
Labels: 🔨 Refactor

#54 [FIX] 에러메세지 관련 수정
  src/main/java/SeoulMilk1_BE/global/apiPayload/exception/ExceptionAdvice.java
Labels: 🐞 BugFix

#56 [FIX] 등록 유저만 로그인 가능하도록 수정
  src/main/java/SeoulMilk1_BE/auth/service/AuthService.java
  src/main/java/SeoulMilk1_BE/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/SeoulMilk1_BE/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/SeoulMilk1_BE/user/exception/UserIsDeletedException.java
  src/main/java/SeoulMilk1_BE/user/exception/UserNotAssignedException.java
Labels: 🐞 BugFix

#58 [FEAT] 관리자 세금계산서 기능
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/AdminSearchTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/AdminSearchTaxResponseList.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/AdminTaxDetailResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/user/controller/AdminController.java
  src/main/java/SeoulMilk1_BE/user/service/AdminService.java
Labels: 📬 API, ✨ Feature

#60 [FEATURE] 관리자 권한으로 지급결의서 조회 기능 추가
  src/main/java/SeoulMilk1_BE/payment_resolution/controller/PaymentResolutionController.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryCustom.java
  src/main/java/SeoulMilk1_BE/payment_resolution/repository/PaymentResolutionRepositoryImpl.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
  src/main/java/SeoulMilk1_BE/user/controller/AdminController.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#62 [FIX] 세금계산서 관련 오류 수정
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepositoryImpl.java
Labels: 🐞 BugFix

#63 [REFACTOR] 지급결의서 작성 시 본인이 담당하는 대리점에 한해서 작성하도록 변경
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
  src/main/java/SeoulMilk1_BE/user/service/TeamService.java
Labels: 📬 API, 🔨 Refactor

#65 [REFACTOR] 관리자 유저 관리 수정
  src/main/java/SeoulMilk1_BE/user/controller/UserController.java
  src/main/java/SeoulMilk1_BE/user/dto/request/UpdateUserRequest.java
  src/main/java/SeoulMilk1_BE/user/repository/UserRepository.java
Labels: 🐞 BugFix, 🔨 Refactor

#66 [REFACTOR] 지급결의서 그룹핑 옵션 변경
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
Labels: 📬 API, 🔨 Refactor

#68 [REFACTOR] 전화번호 관련 수정
  src/main/java/SeoulMilk1_BE/user/controller/UserController.java
  src/main/java/SeoulMilk1_BE/user/domain/User.java
  src/main/java/SeoulMilk1_BE/user/dto/response/HqSearchCsResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/PendingUserResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/UserDetailResponse.java
  src/main/java/SeoulMilk1_BE/user/dto/response/UserManageResponse.java
Labels: 🔨 Refactor

#70 [FEATURE] Open API 액세스 토큰 발급 시 로컬 캐시 활용하여 성능 최적화
  build.gradle
  src/main/java/SeoulMilk1_BE/global/config/ClientConfig.java
  src/main/java/SeoulMilk1_BE/global/config/cache/CacheConfig.java
  src/main/java/SeoulMilk1_BE/global/config/cache/CacheType.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/CodefService.java
Labels: 🌱 Enhance, ✨ Feature, 🔨 Refactor

#72 [FEATURE] WebClient 활용하여 비동기로 외부 API 요청
  build.gradle
  src/main/java/SeoulMilk1_BE/auth/util/RSAUtil.java
  src/main/java/SeoulMilk1_BE/global/config/ClientConfig.java
  src/main/java/SeoulMilk1_BE/nts_tax/controller/NtsTaxController.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/request/CodefValidateRequest.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/CodefService.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/NtsTaxService.java
Labels: 📬 API, 🌱 Enhance, ✨ Feature, 🔨 Refactor

#74 [FEATURE] Covering Index, DTO Projection을 활용하여 지급결의서에 사용되는 세금계산서 컬럼 조회 성능 최적화
  src/main/java/SeoulMilk1_BE/nts_tax/controller/NtsTaxController.java
  src/main/java/SeoulMilk1_BE/nts_tax/domain/NtsTax.java
  src/main/java/SeoulMilk1_BE/nts_tax/dto/response/ForPaymentTaxResponse.java
  src/main/java/SeoulMilk1_BE/nts_tax/repository/NtsTaxRepository.java
  src/main/java/SeoulMilk1_BE/nts_tax/service/NtsTaxService.java
  src/main/java/SeoulMilk1_BE/payment_resolution/dto/request/PaymentResolutionRequest.java
  src/main/java/SeoulMilk1_BE/payment_resolution/service/PaymentResolutionService.java
  src/main/java/SeoulMilk1_BE/user/repository/init/UserInitializer.java
Labels: 📬 API, 🌱 Enhance, ✨ Feature, 🔨 Refactor
